In [9]:
def createFile(filename):
    f=open(filename,"w")
    for i in range(10):
        f.write("This is %d Line\n"%i)
    print('file is created successfully')
    f.close()
    return
createFile("file1.txt")


file is created successfully


In [10]:
def readfile(filename):
    f=open(filename,"r")
    if f.mode=="r":
        x=f.read()
        print(x)
    f.close()
    return
readfile("file1.txt")
        

This is 0 Line
This is 1 Line
This is 2 Line
This is 3 Line
This is 4 Line
This is 5 Line
This is 6 Line
This is 7 Line
This is 8 Line
This is 9 Line



In [1]:



def countlines(filename):
    f=open(filename,"r")
    if f.mode=="r":
        x=f.read()
        lst=x.split("\n")
    return len(lst)
countlines("file1.txt")

11

In [2]:
def datanalysiswordcount(filename,word):
   f=open(filename,"r")
   if f.mode=="r":
       x=f.read()
       lst=x.split()
   cnt=lst.count(word)
   return cnt
print(datanalysiswordcount("file1.txt","rest"))


0


In [3]:


def uppercasecount(filename):
    count=0
    f=open(filename,"r")
    if f.mode=="r": 
            x=f.read()
            lst=list(x)
    for i in lst:
        if i.isupper():
            count = count+1
    
    return count
uppercasecount("file1.txt")

20

In [4]:
def countcharector(filename):
   f=open(filename,"r")
   if f.mode=="r":
       x=f.read()
       lst=list(x)
   return len(lst)
print(countcharector("File1.txt"))


150


In [10]:
import re
def phoneNumberValidate(phone):
    pattern='^[6-9][0-9]{9}$'
    phone=str(phone)
    if re.match(pattern,phone):
        return True
    return False
print(phoneNumberValidate(9966338855))
print(phoneNumberValidate(99668855))


True
False


In [11]:
import re
def phoneNumberValidate(phone):
    pattern='^[6-9][0-9]{9}$|^[0][6-9][0-9]{9}$|[+][9][1][6-9][0-9]{9}$'
    phone=str(phone)
    if re.match(pattern,phone):
        return True
    return False
print(phoneNumberValidate("9899668855"))
print(phoneNumberValidate("09899668855"))
print(phoneNumberValidate("+919899668855"))


True
True
True


In [12]:
import re
def RollNumberValidate(roll):
    pattern='^[1][5][2][U][1][A][0][1-9][0-6][0-9]$'
    roll=str(roll)
    if re.match(pattern,roll):
        return True
    return False
print(RollNumberValidate("152U1A0249"))
print(RollNumberValidate("152U1A0359"))
print(RollNumberValidate("152U1A0379"))


True
True
False


In [16]:
import re
def RollNumberValidate(roll):
    pattern='^[T][S][0-9][0-9][A-Z][A-Z][0-9]{4}$'
    roll=str(roll)
    if re.match(pattern,roll):
        return True
    return False
print(RollNumberValidate("TS13AP8460"))
print(RollNumberValidate("152U1A0359"))
print(RollNumberValidate("152U1A0379"))


True
False
False


In [18]:
import re
def validateEmailID(email):
    pattern='^[0-9a-z][0-9a-z_.]{4,13}[0-9a-z][@][a-z0-9]{3,18}[.][a-z]{2,4}$'
    if re.match(pattern,email):
        return True
    return False
print(validateEmailID("hsjdjdj@gmail.com"))
print(validateEmailID("klkllkolk@gmail.com"))

True
True


In [21]:
import re
def passwordValidation(password):
    pattern = "^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$"
    if re.match(pattern,password):
        return True
    return False
print(passwordValidation("Hdjfdk@123"))
print(passwordValidation("fhj547654353"))


True
False


In [22]:
def createfile(filename):
    f=open(filename,"w")
    for i in range(10):
        f.write(" This is %d line \n" % i)
    print("The file is created and data is stored Successfully")
    f.close()
    return
createfile("f1.txt")
    

The file is created and data is stored Successfully


In [24]:
def appenddata(filename):
    f=open(filename,"a")
    f.write("new line 1\n")
    f.write("newline")
    print("The data is appended")
    return
appenddata("f1.txt")



The data is appended


In [25]:
def countsmall(filename):
    countlower=0
    f=open(filename)
    if f.mode=="r": 
        x=f.read()
        lst=list(x)
    for i in lst:
        if i.islower():
            countlower +=1
    return countlower
    
print(countsmall("f1.txt"))


118


In [26]:
def countdigits(filename):
    c=0
    f=open(filename,"r")
    if f.mode=="r":
        x=f.read()
        lst=list(x)
    for i in lst:
        if i.isnumeric():
            c+=1
    return c
print(countdigits("f1.txt"))



12


In [3]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()
        

test() for the class and method


In [4]:
def test():
    print("test() for function")
    return
test()


test() for function


In [13]:
class Demo1:
    def fact(self,n):
        fact = 1
        while(n!=0):
            fact=fact * n
            n = n-1
        return fact
p1=Demo1()
p1.fact(5)


120

In [19]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2

c1=demo2(10,20)
print(c1.add(100,200))

300


In [21]:
class Person(object):
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())
emp1=Person("XYZ")
print(emp1.getName(),emp1.isEmployee())




Anil False
XYZ False


In [24]:
lst=[1,2,3,4]
print(lst)
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.dtype)
print(array.shape)

[1, 2, 3, 4]
[1 2 3 4]
int32
(4,)


In [31]:
import numpy as np
a=np.array([[4,5,6],[4,5,6]])

b=np.array([[10,20,30],[40,50,60]])
c=np.array(a+b)
print(c)
c.reshape(3,2)

[[14 25 36]
 [44 55 66]]


array([[14, 25],
       [36, 44],
       [55, 66]])

In [32]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))


[1 2 3 4 5 6]


In [33]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))


[[1 2 3]
 [4 5 6]]


In [34]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.07024634 5.7357475  5.13691847 5.18966693 4.92954951 6.15467015
 4.73137115 5.22850947 4.79390249 4.8523176 ]


In [3]:
import numpy as np
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [4]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [5]:
np.arange(1,2048,564)
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [6]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])


slicing column : [2 5]


In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,2])



slicing column : [3 6]


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])


first row : [1 2 3]


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [13]:
a1=np.random.normal(5,0.5,10)
print(a1)
print("Min value= ",np.min(a1))
print("Max value= ",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[5.61652746 5.34568809 5.23626732 4.8283657  5.00993795 4.84786257
 3.88147433 4.98002362 4.30988706 4.68552264]
Min value=  3.881474329461884
Max value=  5.616527463678613
Mean value= 4.874155674760505
Median value= 4.9139430926336765


In [30]:
c1=np.array(([1,2],[3,4]))
c2=np.array(([4,5],[8,9]))
print(c1[0:3,1])

[2 4]


In [2]:
import pandas as pd
dict={"Name":["Sreekar","Surya","Mohit","SATE"],
      "Email ID":["sreekar@yo.com","Surya@skid.com","Mohit@gangleader.com","sate@sate.com"],
      "Mobile Number":["12345678910","1235467098","6543217890","3467853643"],
      "Address":["Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)


      Name              Email ID Mobile Number Address
0  Sreekar        sreekar@yo.com   12345678910     Hyd
1    Surya        Surya@skid.com    1235467098     Hyd
2    Mohit  Mohit@gangleader.com    6543217890     Hyd
3     SATE         sate@sate.com    3467853643     Hyd


In [4]:
import pandas as pd
products=pd.read_csv('Filename.csv')
print(products)

FileNotFoundError: [Errno 2] File b'Filename.csv' does not exist: b'Filename.csv'